version: '3.7'
services:
  lamigra-mysql:
    image: mysql:8.0.28
    container_name: lamigra-mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - lamigra-network
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=streaming
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ./storage/.db:/var/lib/mysql
    security_opt:
      - seccomp:unconfined

  mongodb:
    image: mongo:5.0
    container_name: lamigra-mongo
    ports:
      - 27017:27017
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - lamigra-network

  # lamigra-node:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/node/Dockerfile
  #   container_name: lamigra-node
  #   depends_on:
  #     - lamigra-mysql
  #   networks:
  #     - lamigra-network
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./:/usr/src/

networks:
    lamigra-network:
        name: lamigra-network